# Generated by Django 6.0.6 on 2026-07-01 02:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QARecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='用户问题')),
                ('answer', models.TextField(blank=True, verbose_name='AI回答')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='提问时间')),
            ],
            options={
                'verbose_name': '问答记录',
                'verbose_name_plural': '问答记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
